//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console_Sorgu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitaplar
    {
        public Kitaplar()
        {
            this.Odunc = new HashSet<Odunc>();
        }
    
        public string ISBN { get; set; }
        public string Ad { get; set; }
        public Nullable<int> SayfaSayisi { get; set; }
        public Nullable<int> Stok { get; set; }
        public Nullable<int> TurID { get; set; }
        public Nullable<int> YazarID { get; set; }
        public Nullable<int> YayinEviID { get; set; }
    
        public virtual Turler Turler { get; set; }
        public virtual Yayinevleri Yayinevleri { get; set; }
        public virtual Yazarlar Yazarlar { get; set; }
        public virtual ICollection<Odunc> Odunc { get; set; }
    }
}
