//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console_Sorgu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odunc
    {
        public int ID { get; set; }
        public Nullable<int> UyeID { get; set; }
        public string KitapISBN { get; set; }
        public Nullable<System.DateTime> VerilisTarihi { get; set; }
        public Nullable<System.DateTime> TeslimTarihi { get; set; }
        public Nullable<bool> Iptal { get; set; }
    
        public virtual Kitaplar Kitaplar { get; set; }
        public virtual Uyeler Uyeler { get; set; }
    }
}
