//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console_Sorgu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turler
    {
        public Turler()
        {
            this.Kitaplar = new HashSet<Kitaplar>();
            this.Yazarlar = new HashSet<Yazarlar>();
        }
    
        public int ID { get; set; }
        public string TurAd { get; set; }
    
        public virtual ICollection<Kitaplar> Kitaplar { get; set; }
        public virtual ICollection<Yazarlar> Yazarlar { get; set; }
    }
}
