//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console_Sorgu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yayinevleri
    {
        public Yayinevleri()
        {
            this.Kitaplar = new HashSet<Kitaplar>();
        }
    
        public int ID { get; set; }
        public string Ad { get; set; }
        public string Adres { get; set; }
        public string Tel { get; set; }
    
        public virtual ICollection<Kitaplar> Kitaplar { get; set; }
    }
}
